name: noahhayes
favicon: null
layout_spectrum: 0.8172018195036799
typography_spectrum: 0.36774240829981863
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.519624633481726
  lightness: 0.9003103959839791
  saturation: 0.53521998366341
  rhythmicContrast: 0.21533756726421416
purpose: []
